import { useState } from 'react';
import { motion } from 'framer-motion';

export function ExportPDF({ task, events, finalAnswer, sessionId }) {
  const [exporting, setExporting] = useState(false);

  const exportToPDF = async () => {
    setExporting(true);
    try {
      // Build HTML content for the PDF
      const thoughts = events.filter(e => e.type === 'thought');
      const toolCalls = events.filter(e => e.type === 'tool_call');
      const now = new Date().toLocaleString();

      const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>ARIA Report — ${task.slice(0, 50)}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;600;700&family=JetBrains+Mono:wght@400&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Space Grotesk', sans-serif; background: #fff; color: #1a1a2e; padding: 48px; max-width: 800px; margin: 0 auto; line-height: 1.7; }
  .header { border-bottom: 3px solid #7c5cfc; padding-bottom: 24px; margin-bottom: 32px; }
  .logo { font-size: 28px; font-weight: 700; color: #7c5cfc; letter-spacing: -0.03em; margin-bottom: 4px; }
  .subtitle { font-size: 12px; letter-spacing: 0.2em; text-transform: uppercase; color: #888; }
  .meta { display: flex; gap: 24px; margin-top: 16px; font-size: 12px; color: #666; }
  .task-box { background: #f5f3ff; border: 1px solid #e0d8ff; border-radius: 12px; padding: 20px 24px; margin-bottom: 32px; }
  .task-label { font-size: 11px; letter-spacing: 0.15em; text-transform: uppercase; color: #7c5cfc; font-weight: 600; margin-bottom: 8px; }
  .task-text { font-size: 15px; color: #1a1a2e; }
  .section-title { font-size: 11px; letter-spacing: 0.2em; text-transform: uppercase; color: #888; font-weight: 600; margin: 28px 0 12px; }
  .stat-row { display: flex; gap: 12px; margin-bottom: 24px; }
  .stat { flex: 1; padding: 12px 16px; border: 1px solid #eee; border-radius: 10px; text-align: center; }
  .stat-num { font-size: 22px; font-weight: 700; color: #7c5cfc; }
  .stat-lbl { font-size: 11px; color: #999; margin-top: 3px; }
  .tool-pill { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-family: 'JetBrains Mono', monospace; background: #f0eeff; color: #7c5cfc; margin: 2px; border: 1px solid #e0d8ff; }
  .final-box { background: linear-gradient(135deg, #f0fff8, #f5f3ff); border: 1px solid #a7f3d0; border-radius: 12px; padding: 24px; margin-top: 24px; position: relative; overflow: hidden; }
  .final-box::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px; background: linear-gradient(90deg, #00d4aa, #7c5cfc); }
  .final-label { font-size: 11px; letter-spacing: 0.15em; text-transform: uppercase; color: #00d4aa; font-weight: 600; margin-bottom: 14px; }
  .final-text { font-size: 14px; color: #1a1a2e; white-space: pre-wrap; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; font-size: 11px; color: #bbb; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <div class="logo">◈ ARIA</div>
    <div class="subtitle">Autonomous Research &amp; Intelligence Agent — Session Report</div>
    <div class="meta">
      <span>Session: ${sessionId?.slice(0, 8) || 'unknown'}</span>
      <span>Generated: ${now}</span>
    </div>
  </div>

  <div class="task-box">
    <div class="task-label">Task</div>
    <div class="task-text">${task}</div>
  </div>

  <div class="section-title">Session Statistics</div>
  <div class="stat-row">
    <div class="stat"><div class="stat-num">${thoughts.length}</div><div class="stat-lbl">Thoughts</div></div>
    <div class="stat"><div class="stat-num">${toolCalls.length}</div><div class="stat-lbl">Tool Calls</div></div>
    <div class="stat"><div class="stat-num">${events.filter(e => e.type === 'tool_result').length}</div><div class="stat-lbl">Results</div></div>
    <div class="stat"><div class="stat-num">${events.filter(e => e.type === 'iteration').length > 0 ? Math.max(...events.filter(e => e.type === 'iteration').map(e => e.iteration || 0)) : 0}</div><div class="stat-lbl">Iterations</div></div>
  </div>

  <div class="section-title">Tools Used</div>
  <div style="margin-bottom: 24px;">
    ${[...new Set(toolCalls.map(e => e.tool_name))].map(t => `<span class="tool-pill">${t}</span>`).join('') || '<span style="color:#999;font-size:13px">None</span>'}
  </div>

  ${finalAnswer ? `
  <div class="final-box">
    <div class="final-label">✦ Final Answer</div>
    <div class="final-text">${finalAnswer.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
  </div>
  ` : ''}

  <div class="footer">
    Generated by ARIA · llama-3.3-70b-versatile via Groq · ${now}
  </div>
</body>
</html>`;

      // Open print window
      const printWin = window.open('', '_blank', 'width=900,height=700');
      if (!printWin) { alert('Please allow popups to export PDF.'); setExporting(false); return; }
      printWin.document.write(html);
      printWin.document.close();
      printWin.onload = () => {
        setTimeout(() => {
          printWin.print();
          printWin.close();
          setExporting(false);
        }, 400);
      };
    } catch (err) {
      console.error('Export error:', err);
      setExporting(false);
    }
  };

  if (!finalAnswer) return null;

  return (
    <motion.button
      onClick={exportToPDF}
      disabled={exporting}
      whileTap={{ scale: 0.96 }}
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      style={{
        display: 'flex', alignItems: 'center', gap: 8,
        padding: '9px 18px', borderRadius: 10,
        border: '1px solid rgba(0,212,170,0.3)',
        background: exporting ? 'rgba(0,212,170,0.06)' : 'rgba(0,212,170,0.08)',
        color: '#00d4aa', fontFamily: 'var(--font)',
        fontSize: 13, fontWeight: 600, cursor: exporting ? 'wait' : 'pointer',
        transition: 'all 0.2s',
      }}
      onMouseEnter={e => { if (!exporting) e.currentTarget.style.background = 'rgba(0,212,170,0.15)'; }}
      onMouseLeave={e => { e.currentTarget.style.background = 'rgba(0,212,170,0.08)'; }}
    >
      {exporting ? (
        <>
          <span style={{ width: 14, height: 14, border: '2px solid rgba(0,212,170,0.3)', borderTopColor: '#00d4aa', borderRadius: '50%', display: 'inline-block', animation: 'spin 0.7s linear infinite' }} />
          Exporting…
        </>
      ) : (
        <>⬇ Export PDF</>
      )}
    </motion.button>
  );
}